export const COUNTRY_BY_CODE = {
    AF: 'Afganistán',
    AL: 'Albania',
    DZ: 'Argelia',
    AD: 'Andorra',
    AO: 'Angola',
    AG: 'Antigua y Barbuda',
    AR: 'Argentina',
    AM: 'Armenia',
    AU: 'Australia',
    AT: 'Austria',
    AZ: 'Azerbaiyán',
    BS: 'Bahamas',
    BH: 'Baréin',
    BD: 'Bangladesh',
    BB: 'Barbados',
    BY: 'Bielorrusia',
    BE: 'Bélgica',
    BZ: 'Belice',
    BJ: 'Benín',
    BT: 'Bután',
    BO: 'Bolivia',
    BA: 'Bosnia y Herzegovina',
    BW: 'Botsuana',
    BR: 'Brasil',
    BN: 'Brunéi',
    BG: 'Bulgaria',
    BF: 'Burkina Faso',
    BI: 'Burundi',
    CV: 'Cabo Verde',
    KH: 'Camboya',
    CM: 'Camerún',
    CA: 'Canadá',
    CF: 'República Centroafricana',
    TD: 'Chad',
    CL: 'Chile',
    CN: 'China',
    CO: 'Colombia',
    KM: 'Comoras',
    CG: 'República del Congo',
    CR: 'Costa Rica',
    CI: 'Costa de Marfil',
    HR: 'Croacia',
    CU: 'Cuba',
    CY: 'Chipre',
    CZ: 'República Checa',
    KP: 'Corea del Norte',
    CD: 'República Democrática del Congo',
    DK: 'Dinamarca',
    DJ: 'Yibuti',
    DM: 'Dominica',
    DO: 'República Dominicana',
    EC: 'Ecuador',
    EG: 'Egipto',
    SV: 'El Salvador',
    GQ: 'Guinea Ecuatorial',
    ER: 'Eritrea',
    EE: 'Estonia',
    SZ: 'Esuatini',
    ET: 'Etiopía',
    FJ: 'Fiyi',
    FI: 'Finlandia',
    FR: 'Francia',
    GA: 'Gabón',
    GM: 'Gambia',
    GE: 'Georgia',
    DE: 'Alemania',
    GH: 'Ghana',
    GR: 'Grecia',
    GD: 'Granada',
    GT: 'Guatemala',
    GN: 'Guinea',
    GW: 'Guinea-Bisáu',
    GY: 'Guyana',
    HT: 'Haití',
    HN: 'Honduras',
    HU: 'Hungría',
    IS: 'Islandia',
    IN: 'India',
    ID: 'Indonesia',
    IR: 'Irán',
    IQ: 'Irak',
    IE: 'Irlanda',
    IL: 'Israel',
    IT: 'Italia',
    JM: 'Jamaica',
    JP: 'Japón',
    JO: 'Jordania',
    KZ: 'Kazajistán',
    KE: 'Kenia',
    KI: 'Kiribati',
    KW: 'Kuwait',
    KG: 'Kirguistán',
    LA: 'Laos',
    LV: 'Letonia',
    LB: 'Líbano',
    LS: 'Lesoto',
    LR: 'Liberia',
    LY: 'Libia',
    LI: 'Liechtenstein',
    LT: 'Lituania',
    LU: 'Luxemburgo',
    MG: 'Madagascar',
    MW: 'Malaui',
    MY: 'Malasia',
    MV: 'Maldivas',
    ML: 'Malí',
    MT: 'Malta',
    MH: 'Islas Marshall',
    MR: 'Mauritania',
    MU: 'Mauricio',
    MX: 'México',
    FM: 'Estados Federados de Micronesia',
    MC: 'Mónaco',
    MN: 'Mongolia',
    ME: 'Montenegro',
    MA: 'Marruecos',
    MZ: 'Mozambique',
    MM: 'Myanmar',
    NA: 'Namibia',
    NR: 'Nauru',
    NP: 'Nepal',
    NL: 'Países Bajos',
    NZ: 'Nueva Zelanda',
    NI: 'Nicaragua',
    NE: 'Níger',
    NG: 'Nigeria',
    MK: 'Macedonia del Norte',
    NO: 'Noruega',
    OM: 'Omán',
    PK: 'Pakistán',
    PW: 'Palaos',
    PA: 'Panamá',
    PG: 'Papúa Nueva Guinea',
    PY: 'Paraguay',
    PE: 'Perú',
    PH: 'Filipinas',
    PL: 'Polonia',
    PT: 'Portugal',
    QA: 'Catar',
    KR: 'Corea del Sur',
    MD: 'Moldavia',
    RO: 'Rumania',
    RU: 'Rusia',
    RW: 'Ruanda',
    KN: 'San Cristóbal y Nieves',
    LC: 'Santa Lucía',
    VC: 'San Vicente y las Granadinas',
    WS: 'Samoa',
    SM: 'San Marino',
    ST: 'Santo Tomé y Príncipe',
    SA: 'Arabia Saudita',
    SN: 'Senegal',
    RS: 'Serbia',
    SC: 'Seychelles',
    SL: 'Sierra Leona',
    SG: 'Singapur',
    SK: 'Eslovaquia',
    SI: 'Eslovenia',
    SB: 'Islas Salomón',
    SO: 'Somalia',
    ZA: 'Sudáfrica',
    SS: 'Sudán del Sur',
    ES: 'España',
    LK: 'Sri Lanka',
    SD: 'Sudán',
    SR: 'Surinam',
    SE: 'Suecia',
    CH: 'Suiza',
    SY: 'Siria',
    TJ: 'Tayikistán',
    TH: 'Tailandia',
    TL: 'Timor Oriental',
    TG: 'Togo',
    TO: 'Tonga',
    TT: 'Trinidad y Tobago',
    TN: 'Túnez',
    TR: 'Turquía',
    TM: 'Turkmenistán',
    TV: 'Tuvalu',
    UG: 'Uganda',
    UA: 'Ucrania',
    AE: 'Emiratos Árabes Unidos',
    GB: 'Reino Unido',
    TZ: 'Tanzania',
    US: 'Estados Unidos',
    UY: 'Uruguay',
    UZ: 'Uzbekistán',
    VU: 'Vanuatu',
    VE: 'Venezuela',
    VN: 'Vietnam',
    YE: 'Yemen',
    ZM: 'Zambia',
    ZW: 'Zimbabue',
    VA: 'Ciudad del Vaticano',
    PS: 'Palestina',
} as const;

export type CountryCode = keyof typeof COUNTRY_BY_CODE;
export type CountryName = typeof COUNTRY_BY_CODE[CountryCode];

type Entry = [CountryCode, CountryName];

export const CODE_BY_COUNTRY = (Object
    .entries(COUNTRY_BY_CODE) as Entry[])
    .reduce<Record<CountryName, CountryCode>>((acc, [code, name]) => {
        acc[name] = code;
        return acc;
    }, {} as Record<CountryName, CountryCode>);

export function getCountryName(code: CountryCode): CountryName {
    return COUNTRY_BY_CODE[code];
}

export function getCountryCode(name: CountryName): CountryCode {
    return CODE_BY_COUNTRY[name];
}
